import { type Car } from "../types/car.interface";

export const useItems = () => {
  const cars: Car[] = [
    {
      id: "1",
      nameCar: "bmw",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["/bm-1.jpg", "ww.webp", "pride.webp", "/sa.jpg"],
      tavafogi: true,
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },

    {
      id: "2",
      nameCar: "پرشیا ",
      Description: "به میزبانی کارل فردریکسن",
      tavafogi: true,
      price: 12000000,
      carImg: ["bm-2.jpg", "pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تهران",
    },
    {
      id: "3",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["bm-3.jpg", "pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "سنندج",
    },
    {
      id: "4",
      nameCar: "بنز ",
      Description: "به میزبانی کارل فردریکسن",
      tavafogi: true,
      price: 12000000,
      carImg: ["bm-4.jpg", "pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "اصفهان",
    },
    {
      id: "5",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: [],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "شیراز",
    },
    {
      id: "6",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "7",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "8",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "9",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "10",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "11",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "12",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "13",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "14",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "15",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "16",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "17",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
    {
      id: "18",
      nameCar: "سمند ",
      Description: "به میزبانی کارل فردریکسن",
      price: 12000000,
      carImg: ["pride.webp", "/sa.jpg"],
      salamati: "سالم",
      vazeyat: "بیرنگ",
      tarikh: "1400",
      bime: "دارد",
      km: "1800",
      makan: "تبریز",
    },
  ];
  // const cars2 = ref([]);
  // const fetchCars = ()=>{
  //   const {data} = useFetch("sdfsdf")

  //   cars2.value= data.value.data.cars
  // }

  const favCars = useLocalStorage<Record<string, Car>>(
    "favCars",
    {},
    { initOnMounted: true }
  );
  const favLength = computed(() => Object.keys(favCars.value).length);

  const toggleFav = (item: Car) => {
    //call api
    try {
      // $fetch("http://dfsdf", {
      //   method: "put",
      //   body: { CarId: item.id },
      // });
      if (favCars.value[item.id]) {
        delete favCars.value[item.id];
      } else {
        favCars.value[item.id] = item;
      }
    } catch (e) {
      console.log(e);
    }
  };

  return { cars, favCars, toggleFav, favLength };
};
